# Generated by Django 4.2.1 on 2023-09-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter author name', max_length=200)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=200)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter genre name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter language name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter book title', max_length=200)),
                ('summary', models.CharField(help_text='Enter book summry', max_length=200)),
                ('imprint', models.CharField(help_text='Enter imprint', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='book/%Y/%m/%d')),
                ('ISBN', models.CharField(help_text='Enter ISBN', max_length=200)),
                ('quantity', models.IntegerField()),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('cost', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'available'), ('U', 'unavailable')], help_text='units of product', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.language')),
            ],
        ),
    ]
