# Generated by Django 4.2.1 on 2023-05-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('A', 'available'), ('U', 'unavailable')], default=0, help_text='units of product', max_length=1),
            preserve_default=False,
        ),
    ]
