# Generated by Django 4.2.1 on 2023-09-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_adversisment_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='adversisment',
            name='company_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
