# Generated by Django 4.2.1 on 2023-09-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_adversisment_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
