# Generated by Django 4.2.1 on 2023-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
