# Generated by Django 4.2.1 on 2023-09-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('short_answer', models.CharField(max_length=200)),
                ('full_answer', models.TextField()),
            ],
        ),
    ]
