# Generated by Django 4.2.1 on 2023-09-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_workerposition_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='full_answer',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='short_answer',
        ),
    ]
