FROM python:3.10.6

WORKDIR "/home/denis/Documents/Study/pythn_igi/Lab_2/task2"

COPY ["main.py", "./"]
COPY ["CLI.py", "./"]
COPY ["UniqueContainer.py", "./"]
COPY ["info.txt", "./"]

ENTRYPOINT ["python", "main.py"]