# Generated by Django 4.2.1 on 2023-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
